task:
  type: "material"


credentials:
  openai: creds/openai.txt
  claude: 
  gemini: 

input:
  text_prompt: "Marbled Granite: Enhanced with white and gray streaks and a glossy finish."
  input_image: 
  target_code:

output:
  output_dir: "output/wood_to_marble/"

run_config:
  blender_command: "infinigen/blender/blender"
  edit_style: "rewrite_code"
  num_tries: 4
  enable_visual_imagination: True
  enable_hypothesis_reversion: True
  variants: 
    - "tune_leap"
  tree_dims: 
    - "4x8"
  edit_generator_type: "GPT4V"
  state_evaluator_type: "GPT4V"

  max_concurrent_rendering_processes: 8
  max_concurrent_evaluation_requests: 4
  max_concurrent_generator_requests: 8
